### ISSUE TITLE
Task list for github introduction demos

### ISSUE THREAD

**Issue by vijaykchauhan** [vijaykchauhan/github-intro#1]
- [ ] crate a sample as intro 1, 2, 3 ...
- [ ] add users as collabarator
- [ ] creating branch and merge to master
